# ##################
# Begin ThermIQ #####
# ThermIQ-MQTT configuration.yaml entry
# Set the mqtt_node name here. Thats all!

thermiq_mqtt:
  mqtt_node: ThermIQ/ThermIQ-mqtt
  thermiq_dbg: False

# End ThermIQ ######
# ##################

