# Begin ThermIQ #####
# ThermIQ-MQTT configuration.yaml entry
# Set the mqtt_node name here. Thats all!
thermiq_mqtt:
  mqtt_node: ThermIQ/ThermIQ-mqtt
  thermiq_dbg: False


#Input entities for ThermIQ -> configuration.yaml
input_number:
  thermiq_indoor_requested_t:
    name: 'Indoor target temp.'
    initial: 0
    min:  0
    max:  50
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_integral1_curve_slope:
    name: 'Curve'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_integral1_curve_min:
    name: 'Curve min'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_integral1_curve_max:
    name: 'Curve max'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_integral1_curve_p5:
    name: 'Curve +5'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_integral1_curve_0:
    name: 'Curve 0'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_integral1_curve_n5:
    name: 'Curve -5'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_heating_stop_t:
    name: 'Heatstop'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_reduction_t:
    name: 'Temp. reduction'
    initial: 0
    min:  0
    max:  100
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_room_factor:
    name: 'Room factor'
    initial: 0
    min:  0
    max:  2
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_integral2_curve_slope:
    name: 'Curve 2'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_integral2_curve_min:
    name: 'Curve 2 min'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_integral2_curve_max:
    name: 'Curve 2 max'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_integral2_curve_target:
    name: 'Curve 2, Target'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_integral2_curve_actual:
    name: 'Curve 2, Actual'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_outdoor_stop_t:
    name: 'Outdoor stop temp. (20=-20C)'
    initial: 0
    min:  0
    max:  100
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_preassure_pipe_limit_t:
    name: 'Pressurepipe, temp. limit'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_hotwater_start_t:
    name: 'Hotwater starttemp.'
    initial: 0
    min:  0
    max:  100
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_hotwater_runtime_m:
    name: 'Hotwater operating time'
    initial: 0
    min:  0
    max:  32767
    step: 1
    unit_of_measurement: 'min'
    icon: 'mdi:timer'
    mode: box

  thermiq_heatpump_runtime_m:
    name: 'Heatpump operating time'
    initial: 0
    min:  0
    max:  32767
    step: 1
    unit_of_measurement: 'min'
    icon: 'mdi:timer'
    mode: box

  thermiq_legionella_runtime_m:
    name: 'Legionella interval'
    initial: 0
    min:  0
    max:  32767
    step: 1
    unit_of_measurement: 'days'
    icon: 'mdi:timer'
    mode: box

  thermiq_legionella_stop_t:
    name: 'Legionella stop temp.'
    initial: 0
    min:  0
    max:  100
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_integral1_a_limit:
    name: 'Integral limit A1'
    initial: 0
    min:  -32768
    max:  32767
    step: 1
    unit_of_measurement: 'Cmin'
    icon: 'mdi:speedometer'
    mode: box

  thermiq_integral1_hysteresis_t:
    name: 'Hysteresis, heatpump'
    initial: 0
    min:  0
    max:  100
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_returnline_max_t:
    name: 'Returnline temp., max limit'
    initial: 0
    min:  0
    max:  100
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_start_interval_min_m:
    name: 'Minimum starting interval'
    initial: 0
    min:  0
    max:  32767
    step: 1
    unit_of_measurement: 'min'
    icon: 'mdi:timer'
    mode: box

  thermiq_brine_min_t:
    name: 'Brinetemp., min limit (-15=OFFV)'
    initial: 0
    min:  -25
    max:  100
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_cooling_target_t:
    name: 'Cooling, target'
    initial: 0
    min:  0
    max:  50
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_integral2_a_limit:
    name: 'Integral limit A2'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: '10 Cmin'
    icon: 'mdi:speedometer'
    mode: box

  thermiq_integral2_hysteresis_t:
    name: 'Hysteresis limit, aux'
    initial: 0
    min:  0
    max:  100
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

  thermiq_elect_boiler_steps_max:
    name: 'Max step, aux'
    initial: 0
    min:  -32768
    max:  32767
    step: 1
    unit_of_measurement: 'steps'
    icon: 'mdi:speedometer'
    mode: box

  thermiq_current_consumption_max_a:
    name: 'Electrical current, max limit'
    initial: 0
    min:  -32768
    max:  32767
    step: 1
    unit_of_measurement: 'A'
    icon: 'mdi:speedometer'
    mode: box

  thermiq_shunt_time_s:
    name: 'Shunt time'
    initial: 0
    min:  0
    max:  32767
    step: 1
    unit_of_measurement: 's'
    icon: 'mdi:timer'
    mode: box

  thermiq_hotwater_stop_t:
    name: 'Hotwater stop temp.'
    initial: 0
    min:  0
    max:  100
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature-celsius'
    mode: slider

# #####
input_select:
  thermiq_main_mode:
    name: 'ThermIQ Mode'
    options:
      - 'Off'
      - 'Auto'
      - 'Heatpump only'
      - 'Electric only'
      - 'Hotwater only'
    icon: mdi:power

# End ThermIQ ######

