# Begin ThermIQ #####
# ThermIQ-MQTT configuration.yaml entry
# Set the mqtt_node name here. Thats all!
thermiq_mqtt:
  mqtt_node: ThermIQ/ThermIQ-mqtt
  #thermiq_dbg: True


#Input entities for ThermIQ -> configuration.yaml
input_number:
  thermiq_rum_bor2:
    name: 'Indoor target temp.'
    initial: 0
    min:  0
    max:  50
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature'
    mode: slider

  thermiq_kurva:
    name: 'Curve'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: ''
    icon: 'mdi:speedometer'
    mode: box

  thermiq_kurva_min:
    name: 'Curve min'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: ''
    icon: 'mdi:speedometer'
    mode: box

  thermiq_kurva_max:
    name: 'Curve max'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: ''
    icon: 'mdi:speedometer'
    mode: box

  thermiq_kurva_p5:
    name: 'Curve +5'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: ''
    icon: 'mdi:speedometer'
    mode: box

  thermiq_kurva_0:
    name: 'Curve 0'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: ''
    icon: 'mdi:speedometer'
    mode: box

  thermiq_kurva_n5:
    name: 'Curve -5'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: ''
    icon: 'mdi:speedometer'
    mode: box

  thermiq_varme_stp:
    name: 'Heatstop'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature'
    mode: slider

  thermiq_sankn_t:
    name: 'Temp. reduction'
    initial: 0
    min:  0
    max:  100
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature'
    mode: slider

  thermiq_rumfakt:
    name: 'Room factor'
    initial: 0
    min:  0
    max:  2
    step: 1
    unit_of_measurement: ''
    icon: 'mdi:speedometer'
    mode: box

  thermiq_kurva2:
    name: 'Curve 2'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: ''
    icon: 'mdi:speedometer'
    mode: box

  thermiq_kurva2_min:
    name: 'Curve 2 min'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: ''
    icon: 'mdi:speedometer'
    mode: box

  thermiq_kurva2_max:
    name: 'Curve 2 max'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: ''
    icon: 'mdi:speedometer'
    mode: box

  thermiq_kurva2_bor:
    name: 'Curve 2, Target'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature'
    mode: slider

  thermiq_kurva2_ar:
    name: 'Curve 2, Actual'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature'
    mode: slider

  thermiq_status6:
    name: 'Outdoor stop temp. (20=-20C)'
    initial: 0
    min:  -32768
    max:  32767
    step: 1
    unit_of_measurement: ''
    icon: 'mdi:speedometer'
    mode: box

  thermiq_tryckr_limit:
    name: 'Pressurepipe, temp. limit'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature'
    mode: slider

  thermiq_vv_start:
    name: 'Hotwater starttemp.'
    initial: 0
    min:  0
    max:  100
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature'
    mode: slider

  thermiq_vv_tid:
    name: 'Hotwater operating time'
    initial: 0
    min:  0
    max:  32767
    step: 1
    unit_of_measurement: 'min'
    icon: 'mdi:timer'
    mode: box

  thermiq_varme_tid:
    name: 'Heatpump operating time'
    initial: 0
    min:  0
    max:  32767
    step: 1
    unit_of_measurement: 'min'
    icon: 'mdi:timer'
    mode: box

  thermiq_leg_interv:
    name: 'Legionella interval'
    initial: 0
    min:  0
    max:  32767
    step: 1
    unit_of_measurement: 'days'
    icon: 'mdi:timer'
    mode: box

  thermiq_leg_stop_t:
    name: 'Legionella stop temp.'
    initial: 0
    min:  0
    max:  100
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature'
    mode: slider

  thermiq_integr_a1:
    name: 'Integral limit A1'
    initial: 0
    min:  -32768
    max:  32767
    step: 1
    unit_of_measurement: 'Cmin'
    icon: 'mdi:speedometer'
    mode: box

  thermiq_hyst_vp:
    name: 'Hysteresis, heatpump'
    initial: 0
    min:  0
    max:  100
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature'
    mode: slider

  thermiq_max_ret:
    name: 'Returnline temp., max limit'
    initial: 0
    min:  0
    max:  100
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature'
    mode: slider

  thermiq_min_st_int:
    name: 'Minimum starting interval'
    initial: 0
    min:  0
    max:  32767
    step: 1
    unit_of_measurement: 'min'
    icon: 'mdi:timer'
    mode: box

  thermiq_min_brine_t:
    name: 'Brinetemp., min limit (-15=OFFV)'
    initial: 0
    min:  -25
    max:  100
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature'
    mode: slider

  thermiq_kyla_bor:
    name: 'Cooling, target'
    initial: 0
    min:  0
    max:  50
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature'
    mode: slider

  thermiq_integr_a2:
    name: 'Integral limit A2'
    initial: 0
    min:  0
    max:  200
    step: 1
    unit_of_measurement: '10Cmin'
    icon: 'mdi:speedometer'
    mode: box

  thermiq_hyst_ts:
    name: 'Hysteresis limit, aux'
    initial: 0
    min:  0
    max:  100
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature'
    mode: slider

  thermiq_max_steg_ts:
    name: 'Max step, aux'
    initial: 0
    min:  -32768
    max:  32767
    step: 1
    unit_of_measurement: 'steps'
    icon: 'mdi:speedometer'
    mode: box

  thermiq_max_strom:
    name: 'Electrical current, max limit'
    initial: 0
    min:  -32768
    max:  32767
    step: 1
    unit_of_measurement: 'A'
    icon: 'mdi:speedometer'
    mode: box

  thermiq_shunttid:
    name: 'Shunt time'
    initial: 0
    min:  0
    max:  32767
    step: 1
    unit_of_measurement: 's'
    icon: 'mdi:timer'
    mode: box

  thermiq_vv_stop:
    name: 'Hotwater stop temp.'
    initial: 0
    min:  0
    max:  100
    step: 1
    unit_of_measurement: 'ºC'
    icon: 'mdi:temperature'
    mode: slider

# #####
input_select:
  thermiq_dl:
    name: 'ThermIQ Mode'
    options:
      - 'Off'
      - 'Auto'
      - 'Heatpump only'
      - 'Elecric only'
      - 'Hotwater only'
    icon: mdi:power

# End ThermIQ ######

