      - type: entities
        title: ThermIQ
        theme: default
        show_header_toggle: false
        entities:
          - entity: input_select.thermiq_dl
          - entity: sensor.thermiq_sensor_meassured
          - entity: sensor.thermiq_sensor_target
          - entity: sensor.thermiq_t_ute
          - entity: sensor.thermiq_t_rum_ar
          - entity: sensor.thermiq_t_rum_ar_dec
          - entity: sensor.thermiq_t_rum_bor
          - entity: sensor.thermiq_t_rum_bor_dec
          - entity: sensor.thermiq_t_fram
          - entity: sensor.thermiq_t_retur
          - entity: sensor.thermiq_t_vatten
          - entity: sensor.thermiq_t_brine_ut
          - entity: sensor.thermiq_t_brine_in
          - entity: sensor.thermiq_t_kylning
          - entity: sensor.thermiq_t_fram_shunt
          - entity: sensor.thermiq_stromforbr
          - type: 'custom:text-divider-row'
            text: ts_1
          - entity: binary_sensor.thermiq_ts_1
          - entity: binary_sensor.thermiq_ts_2
          - type: 'custom:text-divider-row'
            text: ^
          - entity: sensor.thermiq_t_fram_bor
          - entity: sensor.thermiq_t_fram_shunt_bor
          - type: 'custom:text-divider-row'
            text: brine
          - entity: binary_sensor.thermiq_brine
          - entity: binary_sensor.thermiq_kompr
          - entity: binary_sensor.thermiq_cirkp
          - entity: binary_sensor.thermiq_varmvatten
          - entity: binary_sensor.thermiq_ts2
          - entity: binary_sensor.thermiq_shuntn
          - entity: binary_sensor.thermiq_shuntp
          - entity: binary_sensor.thermiq_ts1
          - type: 'custom:text-divider-row'
            text: shntgrpn
          - entity: binary_sensor.thermiq_shntgrpn
          - entity: binary_sensor.thermiq_shntgrpp
          - entity: binary_sensor.thermiq_shnt_kyln
          - entity: binary_sensor.thermiq_shnt_kylp
          - entity: binary_sensor.thermiq_akt_kyl
          - entity: binary_sensor.thermiq_pass_kyl
          - entity: binary_sensor.thermiq_larm
          - type: 'custom:text-divider-row'
            text: ^
          - entity: sensor.thermiq_pwm_ut
          - type: 'custom:text-divider-row'
            text: alm_hp
          - entity: binary_sensor.thermiq_alm_hp
          - entity: binary_sensor.thermiq_alm_lp
          - entity: binary_sensor.thermiq_alm_ms
          - entity: binary_sensor.thermiq_alm_blf
          - entity: binary_sensor.thermiq_alm_blt
          - type: 'custom:text-divider-row'
            text: alm_ute
          - entity: binary_sensor.thermiq_alm_ute
          - entity: binary_sensor.thermiq_alm_fram
          - entity: binary_sensor.thermiq_alm_retur
          - entity: binary_sensor.thermiq_alm_vv
          - entity: binary_sensor.thermiq_alm_rum
          - entity: binary_sensor.thermiq_alm_fas
          - entity: binary_sensor.thermiq_alm_ovrh
          - type: 'custom:text-divider-row'
            text: ^
          - entity: sensor.thermiq_behov1
          - entity: sensor.thermiq_behov2
          - entity: sensor.thermiq_tryckr_t
          - entity: sensor.thermiq_hgw_vv
          - entity: sensor.thermiq_integr
          - entity: sensor.thermiq_intgr_steg
          - entity: sensor.thermiq_clk_vv
          - entity: sensor.thermiq_min_time_start
          - entity: sensor.thermiq_sw_ver
          - entity: sensor.thermiq_cirk_speed
          - entity: sensor.thermiq_brine_speed
          - entity: sensor.thermiq_clk_vv_stop
          - entity: input_number.thermiq_rum_bor2
          - entity: input_number.thermiq_kurva
          - entity: input_number.thermiq_kurva_min
          - entity: input_number.thermiq_kurva_max
          - entity: input_number.thermiq_kurva_p5
          - entity: input_number.thermiq_kurva_0
          - entity: input_number.thermiq_kurva_n5
          - entity: input_number.thermiq_varme_stp
          - entity: input_number.thermiq_sankn_t
          - entity: input_number.thermiq_rumfakt
          - entity: input_number.thermiq_kurva2
          - entity: input_number.thermiq_kurva2_min
          - entity: input_number.thermiq_kurva2_max
          - entity: input_number.thermiq_kurva2_bor
          - entity: input_number.thermiq_kurva2_ar
          - entity: input_number.thermiq_status6
          - entity: input_number.thermiq_tryckr_limit
          - entity: input_number.thermiq_vv_start
          - entity: input_number.thermiq_vv_tid
          - entity: input_number.thermiq_varme_tid
          - entity: input_number.thermiq_leg_interv
          - entity: input_number.thermiq_leg_stop_t
          - entity: input_number.thermiq_integr_a1
          - entity: input_number.thermiq_hyst_vp
          - entity: input_number.thermiq_max_ret
          - entity: input_number.thermiq_min_st_int
          - entity: input_number.thermiq_min_brine_t
          - entity: input_number.thermiq_kyla_bor
          - entity: input_number.thermiq_integr_a2
          - entity: input_number.thermiq_hyst_ts
          - entity: input_number.thermiq_max_steg_ts
          - entity: input_number.thermiq_max_strom
          - entity: input_number.thermiq_shunttid
          - entity: input_number.thermiq_vv_stop
          - entity: sensor.thermiq_test_mode
          - entity: sensor.thermiq_status7
          - entity: sensor.thermiq_lang
          - entity: sensor.thermiq_status8
          - entity: sensor.thermiq_fabriksinst
          - entity: sensor.thermiq_reset_dr_tid
          - entity: sensor.thermiq_cal_ute
          - entity: sensor.thermiq_cal_fram
          - entity: sensor.thermiq_cal_ret
          - entity: sensor.thermiq_cal_vv
          - entity: sensor.thermiq_cal_brut
          - entity: sensor.thermiq_cal_brin
          - entity: sensor.thermiq_sys_typ
          - type: 'custom:text-divider-row'
            text: till_fasm
          - entity: binary_sensor.thermiq_till_fasm
          - entity: binary_sensor.thermiq_till_2
          - entity: binary_sensor.thermiq_till_hgw
          - entity: binary_sensor.thermiq_till_4
          - entity: binary_sensor.thermiq_till_5
          - entity: binary_sensor.thermiq_till_6
          - entity: binary_sensor.thermiq_till_opt
          - entity: binary_sensor.thermiq_till_fw
          - type: 'custom:text-divider-row'
            text: ^
          - entity: sensor.thermiq_log_tim
          - entity: sensor.thermiq_brine_tim_on
          - entity: sensor.thermiq_brine_tim_off
          - entity: sensor.thermiq_leg_top_on
          - entity: sensor.thermiq_leg_top_tim
          - entity: sensor.thermiq_dr_tim_vp
          - entity: sensor.thermiq_status10
          - entity: sensor.thermiq_dr_tim_ts1
          - entity: sensor.thermiq_status11
          - entity: sensor.thermiq_dr_tim_vv
          - entity: sensor.thermiq_status12
          - entity: sensor.thermiq_dr_tim_pas_kyl
          - entity: sensor.thermiq_status13
          - entity: sensor.thermiq_dr_tim_akt_kyl
          - entity: sensor.thermiq_status14
          - entity: sensor.thermiq_dr_tim_ts2
          - entity: sensor.thermiq_status15
          - entity: sensor.thermiq_status16